import Head from 'next/head'
import bg from "../public/background.jpg"
import { MdKeyboardArrowRight } from "react-icons/md"
import Link from 'next/link'
import Image from 'next/image'
import logo from "../public/logodark.png"

const Join = () => {

    const styles = {
        background: `white url(${bg.src})`,
        width: '100%',
        height: '100vh',
        backgroundPosition: "center",
        backgroundSize: "cover",
        backgroundRepeat: "no-repeat",

    }

    return (
        <div className=' h-[100vh] pt-24 relative' style={styles}>
            <Head>
                <title>wecome</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <div className='flex justify-center'>
                    <Link href="/">
                        <Image src={logo} alt="logo" width={300} />
                    </Link>
                </div>

                <div className='fixed bottom-0 p-6 pb-10 text-white'>
                    <h1 className="text-2xl font-bold mb-2">
                        Travel Around The World
                    </h1>
                    <p className='text-sm'>Book, check in hotels, appartment and inside request from anywere in the world</p>

                    <div className='flex justify-center space-x-6 mt-8'>
                        <Link href="/signUp">
                            <button className='text-lg py-[5px] font-semibold px-10 bg-white hover:bg-transparent border-2 border-gray-100 hover:text-white text-black rounded-lg'> Join</button>
                        </Link>
                        <Link href="/login">
                            <button className='text-lg py-[5px] font-semibold px-10 border-2 border-gray-100 hover:bg-white rounded-lg hover:text-black'> Login</button>
                        </Link>
                    </div>

                    <Link href="/">
                        <div className='mt-10 flex items-center justify-end cursor-pointer space-x-4 pr-10'>
                            <p>continue as a guest</p>
                            <div className='bg-white text-black flex items-center rounded-sm'>
                                <MdKeyboardArrowRight className='text-xl' />
                            </div>
                        </div>
                    </Link>
                </div>
            </div>
        </div>
    )
}

export default Join